### ISSUE TITLE
Item 遺漏了商品描述欄位

### ISSUE THREAD

**Issue by Lai-YT** [ntut-xuan/FastShop#121]
### 問題

Item 遺漏了 description（商品描述欄位），包含

- 定義的 route 接口
<img src="https://user-images.githubusercontent.com/52515370/209143993-3ca6780c-f7c2-4775-9ab7-38f5feba4adc.png" title="payload of getting items" width="70%">

- 資料庫中儲存的資料欄位

https://github.com/ntut-xuan/FastShop/blob/3abeab21bcda5f9628c0aa69260674c0f120b561/backend/models/__init__.py#L31-L41

**Comment by ntut-xuan** [comment]
Close as fixed the issue.
