### ISSUE TITLE
加入會員註冊頁面

### ISSUE THREAD

**Issue by Lai-YT** [ntut-xuan/FastShop#25]
### 期望

作為一位*消費者*，我希望可以*註冊成為會員*，如此我可以管理個人資訊。

### 實作

- [x] 一個可輸入註冊資料（名稱、姓氏、性別、出生日期、電子郵件地址、密碼）的表單
- [x] 一個按下後將資料送往後端註冊的按鈕

<img src="https://i.imgur.com/MjNRrIB.png" alt="註冊畫面示意圖" width="360">

**Comment by ntut-xuan** [comment]
Finish on PR #30.
