### ISSUE TITLE
新增專案開發規則至 wiki 頁面

### ISSUE THREAD

**Issue by ntut-xuan** [ntut-xuan/FastShop#3]
### 期望

希望 wiki 頁面具有一個專案開發規則，用來規範分支準則、代碼風格等相關規範。

### 實作

- [x] Branching Strategy
- Code Style
  - [x] frontend 
  - [x] backend
- [x]  How to do a Code Review
- [x] How to Write a Git Commit Message

**Comment by Lai-YT** [comment]
關於 backend 的風格規範已經完成，可以麻煩 @ntut-xuan 新增前端的部分嗎？

**Comment by ntut-xuan** [comment]
已完成，請查看確認無虞後 close 這個 issues。

**Comment by Lai-YT** [comment]
看起來一切都很好！
