### ISSUE TITLE
重構 login & register 後端

### ISSUE THREAD

**Issue by Lai-YT** [ntut-xuan/FastShop#39]
因為  API 設計時的 PR 有些龐大，因此將 refactor 的工作獨立出來，預計至少包含：
1. 函式的重新命名
2. 函式的拆解與提取（單一職責）
3. 目錄結構

**Comment by ntut-xuan** [comment]
已知兩個異味程式存在，將在此 issue 上修正。

 - [ ] 拋棄 inner function 的方法，使用 if-else 結構來判斷連接 method 並給予適當的功能。
 - [ ] `validate_email` 函式名稱應改為 `is_valid_email`，用於回傳布林結果並進行判斷。
