### ISSUE TITLE
註冊資料並未正確寫入後端資料庫

### ISSUE THREAD

**Issue by ntut-xuan** [ntut-xuan/FastShop#59]
### 問題

在 `45-complete-frontend-and-backend-communicate` 這個分支中，我們正在實作登入與註冊的前後端溝通細節。

我們發現當使用者進行註冊的時候，進行註冊並註冊成功後，資料並未進入資料庫內。

### 問題檢測細節
```
 - [v] 在註冊頁面填寫註冊資料
 - [v] 在註冊接口上得到 200 OK 的 HTTP Code
 - [x] 資料並未存在於資料庫（使用 DBeaver 進行重整但沒出現） 
```

**Comment by Lai-YT** [comment]
請先將 `develope` 併入 `frontend`，再將 `frontend` 併入 `45-complete*`。
`45-complete*` 是前端的改動，所以一定是從 `frontend` 切出，而 `frontend` 也只能從 `develope` 切出。
要避免分支間橫向的關係。

**Comment by Lai-YT** [comment]
於 6789bd77f3a8331df7fc09578a2f85da24fad138 完成併入，將開始尋找問題 🚀

**Comment by ntut-xuan** [comment]
問題已解決，故關閉這個 issue。
