### ISSUE TITLE
提供關於 route 的 API 文件

### ISSUE THREAD

**Issue by Lai-YT** [ntut-xuan/FastShop#72]
### 期望

身為一位前端的開發者，我希望後端有一份關於 route 的 API 文件，如此我可以很方便地得知如何介接。

預期使用 Flasgger 來建立 API 文件，並使其能夠在 `/apidocs` 查看。

### 實作

- [x] 建立 `/apidocs` 頁面

**Comment by ntut-xuan** [comment]
Pending: Use [Flasgger](https://github.com/flasgger/flasgger) to create Swagger API.
