### ISSUE TITLE
建立 Docker Compose 的 CI 測試

### ISSUE THREAD

**Issue by ntut-xuan** [ntut-xuan/FastShop#75]
### 期望

在距離 `0.1.0` 的 release 版本，我們希望可以有一個 docker compose 的建立 CI，以確保 docker compose 可以正常建立。

### 實作

 - [x] 新增 Docker CI 的 GitHub Action。

**Comment by Lai-YT** [comment]
我把 label 改成 test 哦，因為這是引入新的測試工具，不算功能性的修改。
